// <auto-generated />
using coreMvc.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace coreMvc.Migrations
{
    [DbContext(typeof(coreMvcContext))]
    [Migration("20170908074837_InitialCreate6")]
    partial class InitialCreate6
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("coreMvc.Models.Movies", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<decimal>("Price");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<DateTime>("ReleaseDate");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.HasKey("ID");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("coreMvc.Models.PageEntity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Class");

                    b.Property<int>("Page");

                    b.Property<int?>("PaginationID");

                    b.HasKey("ID");

                    b.HasIndex("PaginationID");

                    b.ToTable("PageEntity");
                });

            modelBuilder.Entity("coreMvc.Models.Pagination", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Display");

                    b.Property<int>("Next");

                    b.Property<string>("NextClass");

                    b.Property<int>("Previous");

                    b.Property<string>("PreviousClass");

                    b.Property<string>("Query");

                    b.HasKey("ID");

                    b.ToTable("Pagination");
                });

            modelBuilder.Entity("coreMvc.Models.PageEntity", b =>
                {
                    b.HasOne("coreMvc.Models.Pagination")
                        .WithMany("Pages")
                        .HasForeignKey("PaginationID");
                });
#pragma warning restore 612, 618
        }
    }
}
